version: '3.9'

services:

  postgres:
<<<<<<< HEAD
    image: postgres:14
=======
    image: postgres:12.0
>>>>>>> 4d7b6d3acf9b6d1affb96fe9be706f4fac25fc16
    container_name: order_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: order_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"     # Broker
      - "15672:15672"   # Dashboard
    networks:
      - order-network

networks:
  order-network:

volumes:
  postgres_data:
